# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sher/Code/python/learnQT/BusInquiry/QueryDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(320, 60, 114, 51))
        self.label.setStyleSheet("font: 57 30pt \"WenQuanYi Zen Hei Sharp\";\n"
"color: rgb(239, 41, 41);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 520, 114, 35))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 160, 701, 321))
        self.plainTextEdit.setStyleSheet("font: 57 18pt \"WenQuanYi Zen Hei Sharp\";")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        self.pushButton.clicked['bool'].connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "线路 X"))
        self.pushButton.setText(_translate("Dialog", "确定"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "汽车南站 => 清浦区政府站 明远路站 公交驾校站 柯山路站 清印集团站 延安路站 前进路站 解放路站 邮政大厦站 环城路站 市二院站 华城公司站 电子市场站 水门桥站 淮海广场站 金马广场站 清中站 淮安车站 人民大会堂站 军营路站 黄河桥站 西马路站 苏北市场站 小营广场站 淮海北路站 左庄站 台州商城站 汽车北站"))
